# Generated by Django 6.0.5 on 2026-05-21 06:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Zaragoza', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_equipo', models.CharField(default='caldera_gas', max_length=30)),
                ('marca_equipo', models.CharField(blank=True, max_length=100)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('codigos_postales', models.TextField(blank=True, help_text='Códigos postales separados por coma (ej: 50001,50002,50003)')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('coordinador', 'Coordinador'), ('tecnico', 'Técnico')], default='tecnico', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=50)),
                ('vehiculo', models.CharField(blank=True, max_length=100)),
                ('max_tareas_dia', models.IntegerField(default=12, help_text='Máximo de tareas por día')),
                ('coordinador', models.ForeignKey(blank=True, limit_choices_to={'rol': 'coordinador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='api.zona')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_turno', models.CharField(choices=[('manana', 'Mañana (8:00-14:00)'), ('tarde', 'Tarde (14:00-20:00)'), ('completo', 'Jornada completa (8:00-20:00)')], default='completo', max_length=20)),
                ('notas_coordinador', models.TextField(blank=True)),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'tecnico'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha'],
                'unique_together': {('tecnico', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='TareaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('tipo_servicio', models.CharField(choices=[('reparacion', 'Reparación'), ('mantenimiento', 'Mantenimiento'), ('montaje', 'Montaje'), ('revision', 'Revisión')], default='mantenimiento', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('incidencia', 'Incidencia'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('hora_estimada', models.CharField(blank=True, max_length=10)),
                ('hora_inicio', models.CharField(blank=True, max_length=10)),
                ('hora_fin', models.CharField(blank=True, max_length=10)),
                ('duracion_estimada', models.IntegerField(default=45)),
                ('descripcion', models.TextField(blank=True)),
                ('incidencia', models.TextField(blank=True)),
                ('prioridad', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=2)),
                ('confirmacion', models.CharField(choices=[('sin_avisar', 'Sin avisar'), ('avisado', 'Avisado'), ('confirmado', 'Confirmado'), ('no_contesta', 'No contesta'), ('no_contesta_dia', 'No contesta (día)'), ('rechazado', 'Rechazado'), ('promovido', 'Promovido')], default='sin_avisar', max_length=20)),
                ('intentos_contacto', models.IntegerField(default=0)),
                ('hora_ultimo_intento', models.CharField(blank=True, max_length=10)),
                ('notas_confirmacion', models.TextField(blank=True)),
                ('es_reserva', models.BooleanField(default=False)),
                ('posicion_reserva', models.IntegerField(blank=True, null=True)),
                ('promovido_desde_reserva', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api.cliente')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api.turno')),
            ],
            options={
                'verbose_name': 'Tarea de turno',
                'verbose_name_plural': 'Tareas de turno',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='api.zona'),
        ),
    ]
