# Generated by Django 6.0.5 on 2026-05-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion_formateada',
            field=models.CharField(blank=True, help_text='Dirección normalizada devuelta por Google Geocoding API', max_length=300),
        ),
        migrations.AddField(
            model_name='cliente',
            name='geocodificado',
            field=models.BooleanField(default=False, help_text='True si la dirección fue validada por Google'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud geocodificada', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud geocodificada', null=True),
        ),
    ]
