# Generated by Django 4.2.30 on 2026-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_geocoding_fields_to_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tareaturno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tareaturno',
            name='tipo_servicio',
            field=models.CharField(choices=[('luz', 'Alonso LUZ'), ('gas', 'Alonso GAS'), ('osmosis', 'Alonso ÓSMOSIS'), ('descal', 'Alonso DESCAL'), ('ozono', 'Alonso OZONO'), ('clima', 'Alonso CLIMA'), ('fotovoltaica', 'Alonso FOTOVOLTAICA'), ('manitas', 'Alonso MANITAS')], default='gas', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
