# Generated by Django 4.2.30 on 2026-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_update_tipo_servicio_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.URLField(blank=True, default='', help_text='URL de la foto del técnico', max_length=500),
        ),
    ]
